Repository epitech-mirroring/MyPandoc, pull requests merged in 2024-04, with the labels that each got.

#10 :sparkles: Create the main data structure
  CHANGELOG.md
  Jenkinsfile
  LICENSE
  examples/syntaxe.json
  examples/syntaxe.md
  examples/syntaxe.xml
  mypandoc.cabal
  package.yaml
  src/DataStruct.hs
  src/Lib.hs
Labels: enhancement

#14 ✨ Make better makefile for the project
  Makefile
Labels: enhancement

#15 :sparkles: Xml parser
  app/Main.hs
  src/DataStruct.hs
  src/ParserData.hs
  src/ParserXml.hs
Labels: enhancement, Parsing

#16 :sparkles: Writer XML
  src/DataStruct.hs
  src/Xml/ParserXml.hs
  src/Xml/WriterXml.hs
Labels: Writing

#17 :sparkles: Add JSON Parsing
  mypandoc.cabal
  src/DataStruct.hs
  src/JSON/ParserJSON.hs
  src/JSON/ParserJSONElements.hs
  src/JSON/ParserJSONHeader.hs
  src/ParserData.hs
  src/XML/ParserXML.hs
  src/XML/ParserXMLElements.hs
  src/XML/ParserXMLHeader.hs
  src/XML/ParserXMLUtils.hs
  src/XML/WriterXML.hs
  src/Xml/ParserXml.hs
  src/Xml/WriterXml.hs
Labels: enhancement, Parsing

#19 :arrow_down: Mardown writter
  examples/syntaxe.md
  src/Markdown/WriterMarkdown.hs
  src/XML/ParserXML.hs
Labels: enhancement

#20 ✍️ Json Writter
  Jenkinsfile
  Makefile
  app/Main.hs
  mypandoc.cabal
  package.yaml
  src/JSON/WriterJSON.hs
  src/Markdown/WriterMarkdown.hs
  src/ParserData.hs
  src/XML/ParserXMLElements.hs
  test/Spec.hs
Labels: enhancement, Writing

#21 :safety_vest: Added commit message validation
  .gitignore
  .husky/commit-msg
  package.json
Labels: enhancement

#23 :building_construction: Add core program
  app/Main.hs
  mypandoc.cabal
  src/Core.hs
  src/Error.hs
  src/HandleArgs.hs
  src/OpenFile.hs
  src/ParserData.hs
  src/XML/WriterXML.hs
Labels: enhancement, Parsing, Core

#30 :bug: Fix section writing in writeMarkdownDocument function
  src/Markdown/WriterMarkdown.hs
Labels: bug, Writing

#29 :bug: Fix bug when the type of input is mardown
  src/Core.hs
  src/OpenFile.hs
Labels: bug, Core

#28 :bug: Fix parsing when the body is empty
  examples/syntaxe_empty.json
  examples/syntaxe_empty.xml
  src/JSON/ParserJSON.hs
  src/XML/WriterXML.hs
Labels: bug, Parsing

#36 :bug: Fix indentation problem at the end of body in WriterXML.hs
  src/XML/WriterXML.hs
Labels: bug, Writing

#41 :white_check_mark: Add DataStructSpecs and ParserDataSpecs to the tests
  mypandoc.cabal
  test/DataStructSpecs.hs
  test/ParserDataSpecs.hs
  test/Spec.hs
Labels: tests

#40 :test_tube: Add test for the core
  test/HandleArgsSpecs.hs
  test/OpenFileSpecs.hs
  test/Spec.hs
  test/test_files/syntaxe.json
  test/test_files/syntaxe.md
  test/test_files/syntaxe.xml
Labels: Core, tests
